// Auto-generated by LibreLane
module top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clkA,
  input reset,
  input spi_ss_n,
  input spi_sclk,
  input spi_mosi,
  output spi_miso,
  input x_serial,
  output y_serial
);
endmodule
